### ISSUE TITLE
When range is used on the first field, it's a byte short.

### ISSUE THREAD

**Issue by David-OConnor** [hashmismatch/packed_struct.rs#100]
Let's say the first field is 7 bytes. I have code like this:

```rust
// #[packed_field(bytes = "0..7")]
#[packed_field(bytes = "0..8")] // bug in packed struct
pub timestamp: u64,
```

It comes out a byte too short otherwise. (Ie when set to 0..7, the first field actually was 6 bytes). Something something hardest problems in programming. ;)

**Comment by rudib** [comment]
The same convention is used here as in Rust's range syntax, so `0..7` would be an exclusive range. Try `0..=7`.

**Comment by David-OConnor** [comment]
How many values are in range `0..7`? How many are in `0..=7`?

When indexing into the first 7 values of an array, what range syntax do you use?
