### ISSUE TITLE
Allow primitive enum to designate a variant for unknown values

### ISSUE THREAD

**Issue by kc8apf** [hashmismatch/packed_struct.rs#25]
In Xilinx configuration bitstreams, packets have a header with opcode, register, and data length fields.  Only some of the possible register values are officially documented.  Bitstreams generated by official tools use undocumented registers.

Right now, I have [this enum](https://github.com/kc8apf/gaffe/blob/master/src/xilinx/xc7/bitstream.rs#L13) to handle this.  packed_struct would be much nicer for the known variants but I explicitly want parsing to succeed and return the unknown variant if an unknown register value is encountered.

I think this can be handled with an extra attribute to designate the unknown variant.  Using a tuple variant prevents using discriminator values though.

**Comment by rudib** [comment]
I've named the feature catch-all primitive enums, per Rust's "_ =>" match arm, but I'm not entirely happy with the name. And a wrapper type named ```EnumWithUnknown``` is even weirder. Anyways, here is a PR with the implementation, I'll try to use it in some of my projects and see if I like it enough. Sample usage, from the test:

```rust
#[derive(PrimitiveEnum_u8, PartialEq, Debug, Clone, Copy)]
pub enum Field {
    A = 1,
    B = 2,
    C = 3
}

#[derive(PackedStruct, Debug, Clone, Copy)]
#[packed_struct(bit_numbering="msb0")]
pub struct Register {
    #[packed_field(bits="0..4", ty="enum")]
    pub field: EnumCatchAll<Field, u8>
}

use packed_struct::prelude::*;

#[test]
fn prim_catch_all() {
    assert_eq!(2, Field::B as u8);

    let r = Register {
        field: Field::B.into()
    };
    let packed = r.pack();
    assert_eq!([0b0010_0000], packed);
    assert_eq!(2, r.field.to_primitive());

    let packed_unknown_value = [0b0100_0000];
    let unpacked_unknown_value = Register::unpack(&packed_unknown_value).unwrap();
    assert_eq!(0b0100, unpacked_unknown_value.field.to_primitive());
    let repacked = unpacked_unknown_value.pack();
    assert_eq!([0b0100_0000], repacked);

    println!("unknown: {:#?}", unpacked_unknown_value);
}
```

**Comment by rudib** [comment]
Version 0.3.0 was released with this feature.
