### ISSUE TITLE
Packing Error on Big Endian Machines

### ISSUE THREAD

**Issue by MichaelDysart** [hashmismatch/packed_struct.rs#47]
This library is pretty cool. I am excited to use it with my projects.

I was looking over the code, and I think that integer packing gives the wrong results on big endian machines.

The algorithm for converting an integer to a big endian byte array is normally as follows:

```
    int number
    byte buffer[4]
    buffer[0] = (byte) number >> 24;
    buffer[1] = (byte) number >> 16;
    buffer[2] = (byte) number >> 8;
    buffer[3] = (byte) number;
```

This algorithm is the same on both big endian and little endian machines. The packet_struct.rs library includes this algorithm in the `as_bytes` macro in https://github.com/hashmismatch/packed_struct.rs/blob/master/packed_struct/src/types_num.rs. For example:

```
    (4, $v: expr) => {
        [
            (($v >> 24) as u8 & 0xFF),
            (($v >> 16) as u8 & 0xFF),
            (($v >> 8) as u8 & 0xFF),
            (($v >> 0) as u8 & 0xFF)
        ]
    };
```

The `as_bytes` macro is used in the `to_msb_bytes` function. However, prior to `as_bytes`, the function `to_le` is called.

```
    #[inline]
    fn to_msb_bytes(&self) -> [u8; $N] {
        let n = self.to_le();
        as_bytes!($N, n)
    }
```

The `to_le` functions behaviour depends on the endianness of the machine. On little endian machines it will leave the byte array unchanged, but on big endian machines it will swap the byte order. This means that on big endian machines the byte order will be swapped prior to writing to the byte array, leading to an incorrect output.

Similar issues exist for the `to_lsb_bytes` and `from_lsb_bytes` functions.

Let me know if I have misunderstood the code in anyway.

Thanks,

**Comment by rudib** [comment]
Hi,

I've used this library on X86/ARM platforms extensively and it performed correctly, therefore I think that the code is doing its job properly. If you can reproduce the problem on a specific platform with a specific example, then please open a detailed bug report. Also, just running the test suite on a Raspberry PI would be good enough, or looking into whether Github's action can add an additional platform for these tests.

It has been a couple of years since I did this, so I could be totally wrong.

**Comment by MichaelDysart** [comment]
Hi,

Thank you for your testing suggestion. I didn't know that it was possible to run tests on multiple architectures through github.

I have setup a fork of this repository to run the unit tests on a variety of architectures (https://travis-ci.org/github/michaeldysart/packed_struct.rs). The tests pass for the three little endian architectures (amd64, arm64, and ppc64le). However, the tests fail for the big endian s390x architecture.

Th unit test logs (https://travis-ci.org/github/MichaelDysart/packed_struct.rs/jobs/737870805) show that the tests failed because the output byte arrays were in the reverse order to the expected byte array. This is the test failure case that is expected to occur as a result of the issue I reported earlier.

The reason you haven't seen the issue before is probably that X86 platforms are little endian. Raspberry PIs also normally run in little endian. Although it is possible to configure the ARM CPU to be big endian, I don't think that the Raspberry PI normally uses that ability.

Let me know if you have any questions.

Thanks,
