### ISSUE TITLE
Unit tests fail on Big Endian Architecture

### ISSUE THREAD

**Issue by MichaelDysart** [hashmismatch/packed_struct.rs#48]
Hi,

As suggested in a comment on #47, I ran the unit tests on multiple architectures, and found that the unit tests fail on big endian machines.

I created a fork of the repository, and ran a Travis CI build on four CPU architectures. The build with the failing tests can be found at https://travis-ci.org/github/michaeldysart/packed_struct.rs.

The unit tests pass on the three little endian machines (AMD64, Arm64, and ppc64le). However, the tests fail on the big endian s390x.

The likely reason for the unit test failure is the issue described in #47. Searching through the logs (https://travis-ci.org/github/MichaelDysart/packed_struct.rs/jobs/737870805), the failing cases often occur when the byte array output by the library is in the opposite order to the expected byte array. For example:
```
---- types_num::test_packed_int_lsb stdout ----
thread 'types_num::test_packed_int_lsb' panicked at 'assertion failed: `(left == right)`
  left: `[221, 204, 187, 170]`,
  right: `[170, 187, 204, 221]`', packed_struct/src/types_num.rs:707:5
```
This is the failure case that is predicted to occur as a result of the issue described in #47.

Let me know if you have any questions. The fork of the repository that is setup to run the tests on multiple architectures is https://github.com/MichaelDysart/packed_struct.rs.

Thanks

**Comment by rudib** [comment]
I've quite recently migrated this repo over to Github Actions, so I don't want to go back to Travis. I'll look if they have a big endian platform that could be used for this, or even if somehow ARM can be easily switched over.

But quite an embarrassing blunder, I've built this lib for bare metal ARM microcontrollers and thought that this was taken care of... Oh well. :)

**Comment by rudib** [comment]
#49 introduces CI for a big endian platform that obviously fails, so we now have a testbed to fix the lib in a new PR :)
