### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by wucke13** [hashmismatch/packed_struct.rs#53]
`packed_struct_codegen` depends on a really old version of `syn`, `v0.11.11` from April 2017. This causes syn to be compiled multiple times, as a new version for serde and an old version for `packed_struct_codegen` are both compiled. It would be cool if `packed_struct` would be modernized a bit in general. This very issue also resulted in the [removal of `packed_struct` as dependency from cranelift](https://github.com/bytecodealliance/cranelift/issues/1271).

**Comment by rudib** [comment]
Too bad that nobody pinged me or opened an issue with those concerns, this was unnoticed by me and I had no idea that it was being used in a quite prominent project... Oh well.

0.4.0 is in the works and a deps upgrade is in order.

The main pipeline bug that prevents me from automating the release process is the cyclical dev dependencies (https://github.com/rust-lang/cargo/issues/4242), but I'd really like to keep the doc-tests for usage examples.

**Comment by wucke13** [comment]
To be fair, I myself on reading issues on some of your other projects got the impression that you were totally unavailable.

> Too bad that nobody pinged me or opened an issue with those concerns, this was unnoticed by me and I had no idea that it was being used in a quite prominent project... Oh well.

That is both good and bad to hear :laughing: . Good as in _they care..._, bad as in _... too late_.

> 0.4.0 is in the works and a deps upgrade is in order.

This is very good news to me! For years I felt like there is a vacuum for building protocols in the Rust ecosystem. There is this crate, but I never really considered it because it seemed to be unmaintained and it pulls in a lot of old (and then redundant) code over the old syn. Also I'm glad that you still exist at all. Maybe you, @amfern and me can also clear out the current mess on crates.io with the fork of the MSP library, but that is another topic...

Is there any rough eta that you can share for this? I would need a modern packed struct for one recent effort of mine, so I got to make the decision whether I will wait for it to become ready or not. Thank you for answering so far! Kind regards

**Comment by amfern** [comment]
Good to hear you are still active and, thank you for this package, it helped me a lot.

**Comment by rudib** [comment]
I've looked into this a bit and here are some of my thoughts:

* The complaint that `packed_struct` is somehow at fault for causing longer compilation times because a different dependency in your project might also use `syn`, but a different version, will probably never be resolved. Both projects would have to have the exact same version and the feature specification! Some of the most popular projects have a pinned version: for instance `serde-derive` uses syn `1.0.33`, `diesel-derive` uses `1.0.1`, etc... As far as I am concerned, Rust is amazing in allowing such dependencies to coexist and it means that projects don't have to be constantly chasing the latest release unless really necessary. 
* I will add the `serde` & `serde-derive` stuff under a feature gate within this lib, I can see how referencing that can cause double-compiles of these libs, but as I mentioned, the versions and features will probably never perfectly match, hence the double-compiles.
* Upgrading to `syn` 1.0 and quote `1.0` seems to be quite a big undertaking, I've opened up #54 for some hacking... Might take a while. But it has to be done so that we can support the latest language syntax.

**Comment by wucke13** [comment]
Regarding your first point, I think you're wrong! [`serde-derive` uses `syn ^1.0.33`](https://crates.io/crates/serde_derive), [`diesel_derives` uses `syn ^1`](https://crates.io/crates/diesel_derives). `^` allows for high versions as long as they are semver compatible. Just try adding both deps to you're cargo toml, and hit `cargo update`. Sure enough only `syn 1.0.53` ends up in the `Cargo.lock` file. Do your research better, next time! Rust is not only amazing in allowing two versions of one dep, but also in using a SAT solver (IIRC) to optimize out the compilation of multiple versions of the same dep - if possible. And this seems to work fine, as I tried it out just now.

Your second point is wrong again, in both subpoints. The second has been debunked above already. Regarding the first: Both of the mentioned packages use a different feature set on `syn`, just check their [`Cargo.toml`s](https://github.com/serde-rs/serde/blob/master/serde_derive/Cargo.toml) and [diesel](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/Cargo.toml). Anyhow, AFAICT only the different files are compiled twice, so the compilation cache is used as efficiently as soundly possible.

>Upgrading to syn 1.0 and quote 1.0 seems to be quite a big undertaking, I've opened up #54 for some hacking... Might take a while. But it has to be done so that we can support the latest language syntax.

Yes it is! I had a look into myself and deemed it unrealistic for me as I do not know the internals of neither packed struct nor syn at all. However, it makes a lot of sense to update such an important dependency to a 1.0 release, now that one is available for quite some time. Bonus points, probably the API will not change in breaking ways in the future, so this will be the last time a big overhaul in this regard is necessary. So, still I can tell that I will appreciate your effort if you do so. Cheers!

**Comment by rudib** [comment]
I spend too much time in the .NET world where the caret is not implied with Nuget :) So that's great news. Also the caching that works across features is also some deep wizardry.

**Comment by rudib** [comment]
FYI, the migration is basically done in PR #54. I'll have to test it with some of my projects that use the lib if it all works fine, but the internal tests pass.
