### ISSUE TITLE
Could 'Integer' implement 'Eq' and 'Hash'?

### ISSUE THREAD

**Issue by njam** [hashmismatch/packed_struct.rs#55]
Currently `Integer` only [implements `PartialEq`](https://docs.rs/packed_struct/0.3.1/packed_struct/types/struct.Integer.html#impl-PartialEq%3CInteger%3CT%2C%20B%3E%3E). Could it also implement `Eq` and `Hash`?

**Comment by rudib** [comment]
Implemented. Will be available in 0.4.0.

**Comment by njam** [comment]
nice, thx!
