### ISSUE TITLE
Wrong packed size?

### ISSUE THREAD

**Issue by zoumi** [hashmismatch/packed_struct.rs#78]
```rust
#[derive(PackedStruct)]
#[repr(C)]
#[packed_struct(endian = "lsb")]
#[derive(Debug, Copy, Clone)]
pub struct Compact{
    pub I: u32,
    pub D1: u8,
    pub D2: [u8; 8usize],
}

fn main()
{
    println!("{0}",std::mem::size_of::<Compact>());
}
```
The size of Compact is 16, but packed_struct.rs packs it to 13 bytes?

**Comment by rudib** [comment]
`size_of::<u32>() + size_of::<u8>() + size_of::<[u8; 8usize]>()` is 13 bytes. 16 bytes is the size of the in-memory structure, with the 3 extra bytes added as padding. Read more into the concepts of memory alignment and padding: 

https://doc.rust-lang.org/reference/type-layout.html
https://en.wikipedia.org/wiki/Data_structure_alignment

This library is generally concerned with packed data which is transferred via the network, memory busses or similar transports.
