### ISSUE TITLE
Can you publish a minor version to crates.io?

### ISSUE THREAD

**Issue by luciusmagn** [hashmismatch/packed_struct.rs#80]
Hi, I'd like to use the quick fix you made for the warnings. Could you publish something like 0.6.1?

**Comment by rudib** [comment]
I need to find some free time, that's all. In the meantime, please look into using a straight git reference to the library using cargo. You might also need to use the patch functionality of cargo.

**Comment by rudib** [comment]
0.6.1 has been released.
