### ISSUE TITLE
Wrong packed struct size?

### ISSUE THREAD

**Issue by gonzalobg** [hashmismatch/packed_struct.rs#85]
The example in the docs is:

```rust
use packed_struct::prelude::*;

#[derive(PackedStruct)]
#[packed_struct(bit_numbering="msb0")]
pub struct TestPack {
    #[packed_field(bits="0..=2")]
    tiny_int: Integer<u8, packed_bits::Bits::<3>>,
    #[packed_field(bits="3..=4", ty="enum")]
    mode: SelfTestMode,
    #[packed_field(bits="7")]
    enabled: bool
}

#[derive(PrimitiveEnum_u8, Clone, Copy, Debug, PartialEq)]
pub enum SelfTestMode {
    NormalMode = 0,
    PositiveSignSelfTest = 1,
    NegativeSignSelfTest = 2,
    DebugMode = 3,
}
```

The docs state that `TestPack` is packed into 1 byte ("Example of a single-byte structure, with a 3 bit integer, primitive enum and a bool field."). However, this fails to compile:

```
let _: [u8; 1] = [0_u8; std::mem::size_of::<TestPack>()];
```

with

```shell
   |     let _: [u8; 1] = [0_u8; mem::size_of::<TestPack>()];
   |            -------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 1 element, found one with 3 elements
   |            |
   |            expected due to this
```

which suggests that the actual size of `TestPack` is 3 bytes, not 1.

**Comment by gonzalobg** [comment]
I think I misunderstood the goal of the crate. It allows converting from/to packed representations, but it does not allow directly operating on them.

**Comment by rudib** [comment]
Yes, that's already built into the language and is highly specific to your target platform: https://doc.rust-lang.org/reference/type-layout.html

This library is for dealing with a known "network" layout and converting from/to that. You can of course combine both the concepts in a single struct.

**Comment by gonzalobg** [comment]
I need to be able to operate in memory to avoid copies, so just moved to use the `bitfield` crate instead. 
Seems to have what I need, but it is a bit painful to use.

**Comment by rudib** [comment]
You might be surprised with how much the Rust compiler can optimize the code in release mode. But, this wasn't my primary motivation for this library, so YMMV.

But, if enough people request it, it should also be possible to create a set of function getters that would retrieve just a single field from the source byte array. Whether that would be more performant is unknown to me.
