### ISSUE TITLE
Use of `a..b` syntax for bits is confusing

### ISSUE THREAD

**Issue by jonas-schievink** [hashmismatch/packed_struct.rs#9]
The readme example contains this:

    #[packed_field(bits="0..2")]
    tiny_int: Integer<u8, packed_bits::Bits3>,

The `bits="0..2"` makes it look like bits 0 and 1 are assigned to the field, because Rust's `x..y` range expression doesn't contain the `y` end point. However this syntax *does* contain bit 2.

To solve this, this library could either change semantics of `bits="a..b"` to exclude `b`, or switch to some inclusive range syntax (possibly both). Rust uses `..=` for inclusive ranges, but those are still unstable (and used to use `...`).

**Comment by rudib** [comment]
The inclusive syntax is specifically written for straightforward implementation of device drivers, as registers maps for devices are usually written in a LSB0 notation with inclusive ranges. For instance, Invensense's popular MPU series of sensors:

![image](https://user-images.githubusercontent.com/835602/35473872-5c8613e6-0386-11e8-859a-d107c1533cb6.png)

Up for discussion, perhaps even a configurable option (if it can be made explicit and obvious enough) and internally, the library actually tracks two bit ranges, one of them being the Rust one.

**Comment by jonas-schievink** [comment]
Yeah, I think it's a good idea to use inclusive ranges to specify bits, but not using Rust's *exclusive* range syntax. Perhaps even the `a:b` syntax could be adopted? Seems to be used in many datasheets.

To make the transition easy, both `a..b` and `a:b` could be accepted, with `a:b` being recommended and used in examples.

> Up for discussion, perhaps even a configurable option (if it can be made explicit and obvious enough)

This can very easily contribute to confusion since the meaning of `a..b` depends on the configuration (even when that is specified in the struct header).

**Comment by rudib** [comment]
Yep, ```a:b``` would make a lot of sense. I'll look into it. The relevant code is around here: https://github.com/hashmismatch/packed_struct.rs/blob/master/packed_struct_codegen/src/pack_parse_attributes.rs#L175
